# Generated by Django 4.1.1 on 2022-09-07 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="New",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("title_en", models.CharField(max_length=150, null=True)),
                ("title_uz", models.CharField(max_length=150, null=True)),
                ("body", models.TextField()),
                ("body_en", models.TextField(null=True)),
                ("body_uz", models.TextField(null=True)),
                ("date", models.DateField()),
            ],
        ),
    ]
