# Generated by Django 4.1.1 on 2022-09-08 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_new_body_alter_new_body_en_alter_new_body_uz_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="new",
            name="body_en",
        ),
        migrations.RemoveField(
            model_name="new",
            name="body_uz",
        ),
        migrations.RemoveField(
            model_name="new",
            name="title_en",
        ),
        migrations.RemoveField(
            model_name="new",
            name="title_uz",
        ),
        migrations.AlterField(
            model_name="new",
            name="body",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="new",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="new",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
