# Generated by Django 4.1.1 on 2022-09-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_new_body_en_remove_new_body_uz_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="new",
            name="body_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="new",
            name="body_uz",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="new",
            name="title_en",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="new",
            name="title_uz",
            field=models.CharField(max_length=150, null=True),
        ),
    ]
